# Use a imagem oficial do Node.js como base
FROM node:latest

# Defina o diretório de trabalho no contêiner
WORKDIR /app

# Copie os arquivos do seu projeto para o diretório de trabalho
COPY . .

# Instale as dependências do projeto
RUN npm install

# Exponha a porta que sua aplicação Next.js está ouvindo
EXPOSE 3000

# Comando para iniciar a aplicação
CMD ["npm", "run", "dev"]
